### PR TITLE
QTGMC update

### PR DESCRIPTION
**Pull request by realfinder**
re-add bomt var
add Refinemotion to presets

also I think there were some bugs in 819d3bd I did fix here

### CODE REVIEW

**Comment by Dogway** [comment]
There's a problem with 8x8 blocksize and hence Refinemotion, if you edit blocksize to 8 here https://github.com/Dogway/Avisynth-Scripts/blob/f579ab9293a329b3f709656107a3e7fe00f708b8/MIX%20mods/QTGMC.avsi#L332 the result would be more like motionblur, I need to investigate further so I you default them to false for the time being I merge.

**Comment by realfinder** [comment]
I didn't get what you mean well but I change it

**Comment by Dogway** [comment]
Thanks

**Comment by Dogway** [comment]
I don't know about 8x8 blocks issue, I have to research, I have been busy with expression optimizations for sharpeners and also updating SMDegrain and a new Deblock Pack. Replied there.

**Pull request merged**
